CoreUpdate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views

from django.urls import path, include

from userextend.forms import AuthenticationNewForm




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('shop.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
    path('', include('cart.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart import views


urlpatterns = [
    path('cart/', views.cart_summary, name='cart_summary' ),
    path('add_cart/', views.cart_add, name='cart_add' ),
    path('delete_cart/', views.cart_delete, name='cart_delete' ),
    path('update_cart/', views.cart_update, name='cart_update' ),
    path('checkout/', views.checkout, name='checkout' ),
]

shop/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save





class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='uploads/categories')
    def __str__(self):
        return self.name


class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, db_index=True)
    brand = models.CharField(max_length=20)
    cpu_socket = models.CharField(max_length=8, null=True, blank=True)
    power_tdp = models.CharField(max_length=6, null=True, blank=True)
    ram_type = models.CharField(max_length=6, null=True, blank=True)
    gpu_type = models.CharField(max_length=6, null=True, blank=True)
    image = models.ImageField(upload_to='uploads/products')

    def __str__(self):
        return f"{self.name} ({self.brand})"


class Order(models.Model):
    class StatusChoices(models.TextChoices):
        ORDERED = 'ordered', 'Ordered'
        DELIVERING = 'delivering', 'Delivering'
        DELIVERED = 'delivered', 'Delivered'

    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, db_index=True)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length=100, default='', blank=True)
    phone = models.CharField(max_length=20, default='', blank=True)
    date = models.DateField(default=datetime.date.today)
    status = models.CharField(
        max_length=20,
        choices=StatusChoices.choices,
        default=StatusChoices.ORDERED,
    )

    def __str__(self):
        return f"Order #{self.id}: {self.product.name} for {self.customer.first_name} {self.customer.last_name} - {self.get_status_display()}"


class OrderNotification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    message = models.TextField(blank=True, null=True)
    sent_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        date_display = self.sent_date.strftime("%Y-%m-%d %H:%M:%S")
        return f"Notification for Order #{self.order.id} - Sent: {date_display}"

templates/category/create_category.html
{% extends 'base.html' %}

{% block title %} Create a new category {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new category</h3>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>  
                </div>    
            </div>
        </div>    
    </div>

{% endblock %}

templates/category/delete_category.html
{% extends 'base.html' %}

{% block title %} Delete trainer {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Delete {{ category }}</h3>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            <p>Are you sure you want to delete {{ category }}?</p>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a href="{% url 'list-of-categories' %}" class="btn btn-secondary">No</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/category/details_category.html
{% extends 'base.html' %}

{% block title %} Details - {{ category }} {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card text-center">
                    <div class="card-header">
                        View details
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ category }}</h5>

                        <a href="{% url 'list-of-categories' %}" class="btn btn-primary">Back to list of categories</a>
                    </div>
                    <div class="card-footer text-body-secondary">
                        Current date: {% now "F j, Y" %}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/category/list_of_categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %} List of categories {% endblock %}

{% block content %}

    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                {% for category in categories %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <a href="{% url 'product-per-category' category.id %}">
                                <img class="card-img-top" src="{{ category.image.url }}" alt="..."/>
                            </a>
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">{{ category.name }}</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
{#                            <div class="dropdown text-center">#}
{#                                <button class="btn btn-secondary dropdown-toggle " type="button"#}
{#                                        data-bs-toggle="dropdown" aria-expanded="false">#}
{#                                    more actions#}
{#                                </button>#}
{#                                <ul class="dropdown-menu">#}
{#                                    <li><a class="dropdown-item"#}
{#                                           href="{% url 'update-categories' category.id %}">Update</a></li>#}
{#                                    <li><a class="dropdown-item"#}
{#                                           href="{% url 'delete-categories' category.id %}">Delete</a></li>#}
{#                                    <li><a class="dropdown-item" href="{% url 'create-categories' %}">Create</a></li>#}
{#                                </ul>#}
{#                            </div>#}
                            {% if perms.category.add_category or perms.category.change_category or perms.category.delete_category %}
                                <div class="dropdown text-center">
                                    <button class="btn btn-secondary dropdown-toggle " type="button"
                                            data-bs-toggle="dropdown" aria-expanded="false">
                                        more actions
                                    </button>

                                    <ul class="dropdown-menu">
                                        {% if perms.category.change_category %}
                                            <li><a class="dropdown-item"
                                                   href="{% url 'update-categories' category.id %}">Update</a></li>
                                        {% endif %}
                                        {% if perms.category.delete_category %}
                                            <li><a class="dropdown-item"
                                                   href="{% url 'delete-categories' category.id %}">Delete</a></li>
                                        {% endif %}
                                        {% if perms.category.add_category %}
                                            <li><a class="dropdown-item" href="{% url 'create-categories' %}">Create</a></li>
                                            
                                        {% endif %}
                                    </ul>
                                </div>

                            {% endif %}
                            <br>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Footer-->


{% endblock %}

templates/category/product_per_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} List of products {% endblock %}

{% block content %}
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                {% for product in get_all_products %}

                    <div class="col mb-5">
                        <div class="card h-100">
                            <a href="{% url 'product-details' product.id %}">
                                <img src="{{ product.image.url }}" class="card-img-top" alt="Image">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title text-left">{{ product.name }}</h5>
                                <p class="card-text">Price: {{ product.price }} RON</p>
                                <p class="card-text">Category: {{ product.category }}</p>
                                <p class="card-text">Brand: {{ product.brand }}</p>
                                {% if product.cpu_socket != None %}
                                    <p class="card-text">CPU Socket: {{ product.cpu_socket }}</p>
                                {% endif %}
                                {% if product.power_tdp != None %}
                                    <p class="card-text">Power TDP: {{ product.power_tdp }} W</p>
                                {% endif %}
                                {% if product.ram_type != None %}
                                    <p class="card-text">RAM Type: {{ product.ram_type }}</p>
                                {% endif %}
                                {% if product.gpu_type != None %}
                                    <p class="card-text">GPU Type: {{ product.gpu_type }}</p>
                                {% endif %}


                            </div>
                            <div class="col md-2 text-center">
                                <a href="{% url 'product-details' product.id %}" class="btn btn-success">View
                                    details</a>
                            </div>
                            <br>


                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>




{% endblock %}

templates/category/update_category.html
{% extends 'base.html' %}
{% block title %} Update category{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Update - {{ category }}</h3>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}