CoreUpdate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views

from django.urls import path, include

from userextend.forms import AuthenticationNewForm




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('shop.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
    path('', include('cart.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart import views


urlpatterns = [
    path('cart/', views.cart_summary, name='cart_summary' ),
    path('add_cart/', views.cart_add, name='cart_add' ),
    path('delete_cart/', views.cart_delete, name='cart_delete' ),
    path('update_cart/', views.cart_update, name='cart_update' ),
    path('checkout/', views.checkout, name='checkout' ),
]

shop/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save





class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='uploads/categories')
    def __str__(self):
        return self.name


class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, db_index=True)
    brand = models.CharField(max_length=20)
    cpu_socket = models.CharField(max_length=8, null=True, blank=True)
    power_tdp = models.CharField(max_length=6, null=True, blank=True)
    ram_type = models.CharField(max_length=6, null=True, blank=True)
    gpu_type = models.CharField(max_length=6, null=True, blank=True)
    image = models.ImageField(upload_to='uploads/products')

    def __str__(self):
        return f"{self.name} ({self.brand})"


class Order(models.Model):
    class StatusChoices(models.TextChoices):
        ORDERED = 'ordered', 'Ordered'
        DELIVERING = 'delivering', 'Delivering'
        DELIVERED = 'delivered', 'Delivered'

    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, db_index=True)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length=100, default='', blank=True)
    phone = models.CharField(max_length=20, default='', blank=True)
    date = models.DateField(default=datetime.date.today)
    status = models.CharField(
        max_length=20,
        choices=StatusChoices.choices,
        default=StatusChoices.ORDERED,
    )

    def __str__(self):
        return f"Order #{self.id}: {self.product.name} for {self.customer.first_name} {self.customer.last_name} - {self.get_status_display()}"


class OrderNotification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    message = models.TextField(blank=True, null=True)
    sent_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        date_display = self.sent_date.strftime("%Y-%m-%d %H:%M:%S")
        return f"Notification for Order #{self.order.id} - Sent: {date_display}"

templates/product/create_product.html
{% extends 'base.html' %}

{% block title %} Create a new product {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new product</h3>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>  
                </div>    
            </div>
        </div>    
    </div>

{% endblock %}

templates/product/delete_product.html
{% extends 'base.html' %}

{% block title %} Delete product {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Delete {{ product }}</h3>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            <p>Are you sure you want to delete {{ product }}?</p>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a href="{% url 'list-of-products' %}" class="btn btn-secondary">No</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/product/details_product.html
{% extends 'base.html' %}

{% block title %} Details - {{ product }} {% endblock %}

{% block content %}


    <br>    <br>    <br>
    <div class="container">
    <br/>
    <div class="card mb-3" >
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
          <div style="text-align: center;">
            <h5 class="card-title">Detalii {{ product }}</h5>
            <p class="card-text">Pret: {{ product.price}} RON</p>
            <p class="card-text">Categorie: {{ product.category}}</p>
            <p class="card-text">Brand: {{ product.brand}}</p>
            {% if product.cpu_socket != None %}  
                <p class="card-text">CPU Socket: {{ product.cpu_socket}}</p>
            {% endif %}  
            {% if product.power_tdp != None %}  
                <p class="card-text">Power TDP: {{ product.power_tdp}} W</p>
            {% endif %}  
            {% if product.gpu_type != None %}  
                <p class="card-text">GPU Type: {{ product.gpu_type}}</p>
            {% endif %}  
            {% if product.ram_type != None %}  
                <p class="card-text">RAM Type: {{ product.ram_type}}</p>
            {% endif %}
                <br/><br/>
            <div class="row justify-content-center">
                <div class="col-md-2">Quantity:</div>
                    <div class="col-md-2">
                        <label>
                            <select class="form-select form-select-sm" id="qty-cart">
                                <option value="1">1</option>
                                <option value="1">2</option>
                                <option value="1">3</option>
                                <option value="1">4</option>
                                <option value="1">5</option>
                            </select>
                        </label>
                    </div>
            </div>
                <br/><br/>
            <button type="button" value="{{ product.id }}" class="btn btn-success" id="add-cart">
                Add to cart
            </button>
            <a href="{% url 'list-of-products' %}" class="btn btn-primary align-center">Back to list of products</a>
          </div>
          </div>
        </div>
      </div>
    </div>
    </div>
    <br/><br/><br/>


<script>

$(document).on('click', '#add-cart', function(e){
    e.preventDefault();
    $.ajax({
        type: 'POST',
        url: '{% url 'cart_add' %}',
        data: {
            product_id: $('#add-cart').val(),
            product_qty: $('#qty-cart option:selected').text(),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
        },

        success: function(json){
            document.getElementById('cart_quantity').textContent=json.qty
            location.reload()
        },

        error: function(xhr, errmsg, err){
        
        }   
    });


    })
</script>
{% endblock %}

templates/product/list_of_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %} List of products {% endblock %}

{% block content %}


    <div class="container-fluid">
        <div class="row" style="padding-top: 10px;padding-bottom: 10px">
                <div class="col-md-2 align-left">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="text-center">Filters</h3>
                        </div>
                        <form method="GET">
                            <div class="card-body">
                                {{ filters_form }}
                            </div>
                            <div class="card-footer text-center">
                                <button type="submit" class="btn btn-outline-success">Filter</button>
                                <a href='{% url 'list-of-products' %}' class="btn btn-outline-danger">Reset</a>
                            </div>
                        </form>
                    </div>
                </div>

                {% for product in all_products %}
                
                <div class="col-md-2">
                    <div class="card">
                        <a href="{% url 'product-details' product.id %}">
                            <img class="card-img-top" src="{{ product.image.url }}" alt="..."/>
                        </a>
                        <div class="card-body p-4">
                            <div class="text-left">
                                <h5 class="card-title text-left">{{ product.name }}</h5>
                                <p class="card-text">Price: {{ product.price }} RON</p>
                                <p class="card-text">Category: {{ product.category }}</p>
                                <p class="card-text">Brand: {{ product.brand }}</p>
                                {% if product.cpu_socket != None %}
                                    <p class="card-text">CPU Socket: {{ product.cpu_socket }}</p>
                                {% endif %}
                                {% if product.power_tdp != None %}
                                    <p class="card-text">Power TDP: {{ product.power_tdp }} W</p>
                                {% endif %}
                                {% if product.ram_type != None %}
                                    <p class="card-text">RAM Type: {{ product.ram_type }}</p>
                                {% endif %}
                                {% if product.gpu_type != None %}
                                    <p class="card-text">GPU Type: {{ product.gpu_type }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="col md-2 text-center">
                            <a href="{% url 'product-details' product.id %}" class="btn btn-success">View details</a>
                        </div>    
                        <br>
                            {% if perms.product.add_product or perms.product.change_product or perms.product.delete_product%}
                            <div class="dropdown text-center">
                                <button class="btn btn-secondary dropdown-toggle " type="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                    more actions
                                </button>
                                
                                    <ul class="dropdown-menu">
                                        {% if perms.product.change_product %}
                                            <li><a class="dropdown-item"
                                                   href="{% url 'update-products' product.id %}">Update</a></li>
                                        {% endif %}
                                        {% if perms.product.delete_product %}
                                            <li><a class="dropdown-item"
                                                   href="{% url 'delete-products' product.id %}">Delete</a></li>
                                        {% endif %}
                                        {% if perms.product.add_product %}
                                            <li><a class="dropdown-item" href="{% url 'create-products' %}">Create</a></li>
                                        {% endif %}
                                    </ul>
                            </div>
                            
                            {% endif %}
                        <br>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/product/update_product.html
{% extends 'base.html' %}
{% block title %} Update product{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Update - {{ product }}</h3>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}